### ISSUE TITLE
Callback "Submitted via" not displaying correct server in Signing Request

### ISSUE THREAD

**Issue by scottoau** [greymass/anchor#894] opened 2020-05-27 12:57 UTC
Using Anchor with a Private Chain, I have deployed an internally networked callback service (buoy-js) and updated the code to reflect the new service location.

Transactions are flowing, CB is working well however, I've noticed on the "Signing Request" pop up the callback link is incorrectly displayed and doesn't reflect my service address. 

<img width="932" alt="Screen Shot 2020-05-27 at 10 30 15 pm" src="https://user-images.githubusercontent.com/40372886/83021074-c62d6f80-a06c-11ea-95d8-d8c6dba7d6fc.png">

Additionally, the clickable transaction_id links to bloks which is fine for public networks, but doesn't work on our private version. 

Is it possible to dynamically update the cb link and would it be possible to specify a block explorer in the configuration of the chain, perhaps overriding the default? 

Thanks for all the amazing work!

**Comment by aaroncox** [comment] 2020-05-28 00:42
A few things to unpack here, so to start the links to explorers. The explorer linking code right now is pretty ancient (from eos-voter) and could really use a rework, which I think we'd probably have to do in advance of being able to manually override it with custom explorers. 

It shouldn't however be clickable and go to bloks.io, I think that's a bug. 

Next up is where it's saying it's being submitted to, being cb.anchor.link. From what I can tell in the code, I think it is actually using that URL. We're reading it directly from the incoming request from what I can tell. Maybe there's a bug in anchor-link or one of the wallet providers that's not allowing this to be set. What are you running again to handle these sessions on the dapp side - link, UAL, or transit?

And the last little bit is about it being incorrectly displayed - that's intentional. Right now I'm considering the UUID in the URL to be privacy related information that you wouldn't want in screenshots (like we see in this github issue). If I knew your session ID, I wouldn't be able to read or write to your session channel, but I could observe when activity was happening between you and an application. 

That might be an overly paranoid reason to strip the UUID out of the URI, but it was low effort and when we made that change I figured it was better to be safe than sorry.

**Comment by scottoau** [comment] 2020-05-28 10:23
Thanks, @aaroncox. We're using `ual-anchor` on the dapp side.

```
    const anchor = new Anchor([chain], {
      appName: 'ual-anchor-demo',
      // Optional: Callback service URL, defaults to cb.anchor.link.
      service: `${ANCHOR_CALLBACK_SERVICE}`,
    });
```
I can see in the browser WebSocket traffic going to the internal link, can also see it on our LB so that's looking good. 

If it's possible to do something about the links, it would really help. 

Also, understand the privacy aspect and makes perfect sense to me. 

Thanks again.

**Comment by aaroncox** [comment] 2020-05-28 19:16
Which version of `ual-anchor` is it? We're up to 0.4.1 now, but I think the hardcoded version that had cb.anchor.link as the domain was fixed in 3.2 🤔

**Comment by scottoau** [comment] 2020-05-28 22:40
I thought I was using 0.3.2, I reinstalled the packages and now I get the correct link! Plus the transaction id is no longer clickable. 

I also tried version 0.4.1 but got different behaviour than previous when signing. I'm seeing the "Action to Perform" window asks for the signature of the user's account, rather than the signature of the action itself. In my setup, I have delegated named users who can sign contract actions. The name of the account will be different from the required Authorizations. 

Did this change from version 0.3.2 to 0.4.1? 

Hopefully, this makes sense.

**Comment by scottoau** [comment] 2020-06-02 04:54
@aaroncox just wanted to double-check if the behaviour is changing as per above? 

Thanks.

**Comment by aaroncox** [comment] 2020-06-02 06:51
Sorry I dropped the ball on following up.

Yeah - 0.4.1 is slightly different than the 0.3.x versions, we modified a few things to more closely match how eosjs works to avoid confusion developers with two different `transact` methods. This might have impacted how you were using it.

Would you mind sharing the URI of an example signing request, and what you're expecting it to do?

**Comment by scottoau** [comment] 2020-06-02 07:26
Yeah no problems. Here is one 

esr://gmO8VMJQcP_FMnW_Hpap4rOVPrzZ2ePY9qWI7RrvhiWGCdveMin_vxo3b-PNvt0sDEDA6LAuKU3q5FlfEOfJ6g8lKAIr3hoZecAE9gdxgcQYhJPy80qLFVKKEssV0vKLFIwMjCz4g12d4x2dQ-K9Qv2AfFMGB13_yT2sDAwHQis2rmZlYAbKMTBZZ5SUFBRb6esnJ-kl5iVn5Bfp5WTmZeubWiSZpFgkJukap1kY6pokpyXrWqYmGugaW1okJRpYJltaGqUxchellpQW5cUXJJZkaMAMyslPTszJyC8usTI2MDDQz0st1we5SznLy9Uwrbw0FQA

**Comment by aaroncox** [comment] 2020-06-02 17:30
So based on that request, I'm seeing: 

```json
{
  "chain_id": [
    "chain_id",
    "D2740070DFE8A6274E8C0495179B22F0ECB98C4186F47206D60DB0A43160B6ED"
  ],
  "req": [
    "transaction",
    {
      "expiration": "2020-06-02T07:26:27.000",
      "ref_block_num": 45470,
      "ref_block_prefix": 79400665,
      "max_net_usage_words": 0,
      "max_cpu_usage_ms": 0,
      "delay_sec": 0,
      "context_free_actions": [],
      "actions": [
        {
          "account": "drawmanager4",
          "name": "insert",
          "authorization": [
            {
              "actor": "drawmanager4",
              "permission": "active"
            }
          ],
          "data": "40AE62661AC9CD4DBF520A000000000013626F6E7573206472617720666F7220323032380F5345435F4143545F4A554E3230323500402D4F938C050000C05578B1AB050003414354"
        }
      ],
      "transaction_extensions": []
    }
  ],
  "flags": 2,
  "callback": "https://cb.anchor.link/58b4d8ab-3f81-4cfc-9ea0-398ba09c992f",
  "info": [
    {
      "key": "return_path",
      "value": "68747470733A2F2F6C6F63616C686F73743A333030302F6E65772F64726177236A4A453166777565"
    }
  ]
}
```
Are you looking for the Anchor wallet currently loaded to sign with the currently loaded account despite the authorization not matching, or is this some sort of setup using account authorizations?

**Comment by scottoau** [comment] 2020-06-03 02:29
The `drawmanager4@active` permission is delegated to the `drawmanager` account (simulating a group), which then has about 5 named accounts <user1>@active, <user2@active>, etc. Does that make sense? 

It works great in ual-anchor 0.3.2. I tried 0.4.1, the only way I could sign was to have the `drawmanager4@active' key in the wallet. Unless I was doing something wrong.

**Comment by aaroncox** [comment] 2020-06-03 17:12
Yeah, that makes sense. 

I'm digging through the UAL code to see what could have possible broken this use case.

One thing I'd invite you to try is the 1.0.4 pre-release and see if it now works:

https://github.com/greymass/anchor/releases/tag/v1.0.4

We removed the authorization checks on the request signing and are just going to let the API itself reject the transaction if it's invalid. That might allow the signature to be generated with `ual-anchor@0.4.1` now.

**Comment by scottoau** [comment] 2020-06-08 05:54
Thanks, @aaroncox I've tried 0.4.1 with 1.0.4 and see the same behaviour. Anchor signs with Authorisation of the account in the wallet, rather than the authorisation of the contract action. This fails in my case. 

Switching back to 0.3.2, no problems.

Thanks!

**Comment by aaroncox** [comment] 2020-06-08 15:39
Alright, so we can rule Anchor out as being part of the problem I think. 

The ESR link you sent before - was this from the working version (0.3.2) or the broken version (0.4.1)?

This ones been very hard to track down simply because we can't reproduce against your private chain 🙁

**Comment by scottoau** [comment] 2020-06-08 22:08
Here is a couple of new ESRs and the error message. Thanks for looking into this one. 

**Working 0.3.2**

`esr://gmO8VMJQcP_FMnW_Hpap4rOVPrzZ2ePY9qWI7RrvhiWGCdveMi3Zei_OUK5K2oabAQgYHdYlpUmdPOsL4qzICbqKKvDWyMgIJrDkDiNIjIGVAQKYGFABZ0pRYnlaZk5qMQOTQ0ZJSUGxlb5-cpJeSWJJSXFefl5BUX6KXnJ-rr6RZUpKmmlimq6hUVqirkmSuZFuokGKia5hiqlhkqVxSmKamRkjd1FqSWlRXnxBYkmGGcy0nPzkxJyM_OISK2MDAwN9kIXF-kZ5KckZiXnJqfqGRkYGRgbK5lllpv6Jlv4A`

**Not working 0.4.1**

`esr://gmO8VMJQcP_FMnW_Hpap4rOVPrzZ2ePY9qWI7RrvhiWGCdveMjisS0qTOnnWlwEIVuQEXWUUcJrRdXmO5iGwwFsjIyOYiiV3GEFiDKwMEMDCgAo4U4oSy9Myc1KLmRwySkoKiq309ZOT9EoSS0qK8_LzCoryU_SS83P1ky0SDVJNzVN0k40MDHRNksyNdS2NzQx1LVJNDU0szcyNU4ySGLmLUktKi_LiCxJLMsxgpuXkJyfmZOQXl1gZGxgY6IPsK9Y3yktJzkjMS07VNzQyMjAyUI708XIxsgyoBAA`

error: Error - could not update draw!
(missing authority of drawmanager4)

**Comment by aaroncox** [comment] 2020-06-08 23:12
Perfect, I think I see the difference which might be the cause. I'll see if I can get a fix in place and release an 0.4.2 for testing.

**Comment by aaroncox** [comment] 2020-06-08 23:39
For reproducing purposes, would you mind sharing in your code how you're issuing the transaction?

I'm assuming it's something like this, but wanted to confirm exactly the syntax being passed into `signTransaction`. 

```js
      const response = await activeUser.signTransaction({
        expiration: '2020-06-08T22:03:16.000',
        ref_block_num: 7729,
        ref_block_prefix: 188488570,
        max_net_usage_words: 0,
        max_cpu_usage_ms: 0,
        delay_sec: 0,
        context_free_actions: [],
        transaction_extensions: [],
        actions: [...]
      })
```

**Comment by scottoau** [comment] 2020-06-09 00:54
Looks like we're doing it this way.

```
  sign = async () => {
    const {
      ual: { activeUser },
    } = this.props;
    try {
      const { accountName, requestPermission } = activeUser;
      const updateTransaction = getTransaction(
        accountName,
        requestPermission,

        <bunch of fields, shortend>

      );
      const result = await activeUser.signTransaction(updateTransaction, {
        broadcast: true,
        expireSeconds: 120,
        blocksBehind: 3,
      });
```
I haven't included `getTransaction()`.

**Comment by aaroncox** [comment] 2020-06-23 21:07
1.0.5 is available now for use - let me know if this resolves any outstanding issues, or where we are with things.

**Comment by scottoau** [comment] 2020-06-24 01:22
@aaroncox thanks for the updates. I'm still seeing the same behaviour, which is different from `ual-anchor` 0.3.2. 

I'm trying to sign this one.

`esr://gmO8VMJQcP_FMnW_Hpap4rOVPrzZ2ePY9qWI7RrvhiWGCdveMjisS0qTOnnWlwEIVuQEXWUUcJrRdXmO5iGwwFsjIyOYilJRZpAYAyMDAwoNA5wpRYnlaZk5qcVMDhklJQXFVvr6yUl6JYklJcV5-XkFRfkpesn5ufomyaaJppapybppqUbJuibmFqm6ieZmabrJKYkWJsYpZgZJBmmM3EWpJaVFefEFiSUZZjDTcvKTE3My8otLrIwNDAz0QfYV6xvlpSRnJOYlp-obGRgZGhgqp6ammZlFeZQAAA`

The required Authorization is drawmanager4@active. My key should have permissions as per below. 

Account - drawmanager4
![image](https://user-images.githubusercontent.com/40372886/85485556-54fdbf80-b60c-11ea-890f-ec3d4e9b0de0.png)

Account - drawmanager
![image](https://user-images.githubusercontent.com/40372886/85485638-79599c00-b60c-11ea-949b-9ed53fb28bed.png)

Let me know if you need more info! Thanks.

**Comment by aaroncox** [comment] 2020-06-24 16:51
Hrm, when I look at the signing request you shared in the above message, it resolves to:

```{
  chain_id: [
    'chain_id',
    'D2740070DFE8A6274E8C0495179B22F0ECB98C4186F47206D60DB0A43160B6ED'
  ],
  req: [
    'action',
    {
      account: 'drawmanager4',
      name: 'update',
      authorization: [ { actor: 'scottowen111', permission: 'active' } ],
      data: '40AE62661AC9CD4D7515030000000000010000000000000001000000000000000000000000000000096472617766696C6573'
    }
  ],
  flags: 2,
  callback: 'https://cb.tattsnonprod.com/4c5a59ec-fe2c-478e-a76f-cda843d60b0f',
  info: [
    {
      key: 'return_path',
      value: '68747470733A2F2F6C6F63616C686F73743A333030302F64726177732F326E646368616E63652F3230323130312365656636365A4874'
    }
  ]
}```

`scottowen111` is the actual authorization on the action, as opposed to `drawmanager4`. 

Going back to your [comment from a few weeks ago](https://github.com/greymass/anchor/issues/894#issuecomment-640913158), when I look at that transaction, I am actually seeing `drawmanager4`. 

```{
  chain_id: [
    'chain_id',
    'D2740070DFE8A6274E8C0495179B22F0ECB98C4186F47206D60DB0A43160B6ED'
  ],
  req: [
    'transaction',
    {
      expiration: '2020-06-08T22:03:16.000',
      ref_block_num: 7729,
      ref_block_prefix: 188488570,
      max_net_usage_words: 0,
      max_cpu_usage_ms: 0,
      delay_sec: 0,
      context_free_actions: [],
      actions: [
        {
          account: 'drawmanager4',
          name: 'update',
          authorization: [ { actor: 'drawmanager4', permission: 'active' } ],
          data: '40AE62661AC9CD4DA4DC010000000000050000000000000002000000000000000000000000000000096472617766696C6573'
        }
      ],
      transaction_extensions: []
    }
  ],
  flags: 2,
  callback: 'https://cb.tattsnonprod.com/29ddf5af-12fa-4b72-a0d4-1d51b93daf66',
  info: [
    {
      key: 'return_path',
      value: '68747470733A2F2F6C6F63616C686F73743A333030302F64726177732F326E646368616E63652F31323230323023376A76354F61394F'
    }
  ]
}```

I don't think anywhere in the code are we changing/altering what's being passed in the `req` data itself - any idea why that'd be happening from your side? 🤔  

Not only that, but I also noticed the transaction from 0.3.2 is a `transaction` request, as opposed to the newer versions which seem to be compressing this down to an `action` request. I'm not sure if that has any bearing on what's happening here, but thought it was interesting to note.

**Comment by scottoau** [comment] 2020-06-24 22:30
I also noticed this a few weeks back. In the older versions, 0.3.2, at the bottom of the signing window, Anchor would populate drawmanager4@active as the required permission, however, in the dropdown I had selected the scottowen111 key to sign the transaction. That would work.

Following the same process on newer versions, Anchor populates scottowen111@active key at the bottom of the window, this fails because scottowen111@active doesn't have direction permission on the action.  

![image](https://user-images.githubusercontent.com/40372886/85633969-bf226d00-b6bd-11ea-929b-0fab9e7091ca.png)

I'll do some more investigation. Using permissions in this sort of group delegation model is pretty useful so hopefully, it's possible. Thanks again.

**Comment by scottoau** [comment] 2020-06-24 23:21
@aaroncox I redeployed using `ual-anchor` 0.3.2 and `anchor` 1.0.5. It works correctly, based on my understanding of permissions (which isn't great!). 

There is also a nice message that pops up in 1.0.5 which is new. Here are the screenshots. 

Signing Request

![image](https://user-images.githubusercontent.com/40372886/85636739-a4072b80-b6c4-11ea-82c2-30e033bee9b1.png)

Signatures Required

![image](https://user-images.githubusercontent.com/40372886/85636771-b8e3bf00-b6c4-11ea-8a0f-dbd3831703a0.png)

**Comment by aaroncox** [comment] 2020-06-25 00:13
Would you mind sharing some additional data from [the example you gave a few weeks back](https://github.com/greymass/anchor/issues/894#issuecomment-640964021)? 

Specifically this bit:

```js
const updateTransaction = getTransaction(
  accountName,
  requestPermission,
  <bunch of fields, shortend>
);
```

I'd be curious to know what a `console.log(updateTransaction)` yields right after that, to know what data is exactly being passed in to:

```js
const result = await activeUser.signTransaction(updateTransaction, {
  broadcast: true,
  expireSeconds: 120,
  blocksBehind: 3,
});
```

**Comment by scottoau** [comment] 2020-06-25 05:05
@aaroncox I've forwarded you the files. Hope they make sense.

**Comment by aaroncox** [comment] 2021-04-06 20:27
I'm going to close this one out for the time being, mainly because it hasn't gotten much attention over the past 6 months. 

At this point I'm not sure if you found a workaround or ifs this is working now - but if you run into instances where this is still misbehaving, lets open up some new individual issues to address those fresh.

**Closed by aaroncox** 2021-04-06 20:27 UTC
