### ISSUE TITLE
Anchor Error when selecting resources

### ISSUE THREAD

**Issue by whofford** [greymass/anchor#1221] opened 2021-11-30 17:58 UTC
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bcolor%2C%20content%2C%20size%2C%20style%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _s (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:51587)
    at file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:56461
    at Ti (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:65888)
    at Li (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:70071)
    at Ri (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:69769)
    at ga (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:105568)
    at lu (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:96815)
    at au (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:96740)
    at $a (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:93770)
    at file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:45412

**Comment by aaroncox** [comment] 2021-12-03 06:27
Which version of Anchor (shows in the title bar) and which blockchain?

**Comment by dignityinside** [comment] 2021-12-04 05:56
Get the same error on Linux Mint 20.1 Cinnamon.

Anchor Version: 1.3.2

**Comment by aaroncox** [comment] 2021-12-05 23:42
When you say "Selecting resources", what specifically are you trying to do? 

I just checked the resources section in 1.3.2 on multiple blockchains and couldn't reproduce the error.

**Comment by whofford** [comment] 2021-12-09 00:12
UTX and my wallet shows version 1.2.2 I open the wallet and all accounts
are locked. If try to go to resources I get the error message.  If I
refresh and unlock all wallets and click resources that works

Regards,
Bill

**Comment by aaroncox** [comment] 2021-12-15 20:59
Thanks for the info - hopefully we'll get a chance to look at this in the not too distant future!

**Comment by aaroncox** [comment] 2022-04-06 22:09
I believe this issue was resolved in a more recent release, but the ticket just never closed.

Closing it out now - but feel free to open a new issue if you're still experiencing issues.

**Closed by aaroncox** 2022-04-06 22:09 UTC
