### ISSUE TITLE
Random popups "Error: WebSocket is not open: readyState 2 (CLOSING)"

### ISSUE THREAD

**Issue by CherryDT** [greymass/anchor#1158] opened 2021-08-23 11:36 UTC
While Anchor is running in the background, I'm randomly getting this popup:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: WebSocket is not open: readyState 2 (CLOSING)
    at j.send (C:\Program Files\Anchor Wallet\resources\app.asar\webpack:\app\main.prod.js:213491:19)
    at j.<anonymous> (C:\Program Files\Anchor Wallet\resources\app.asar\webpack:\app\main.prod.js:50718:32)
    at j.emit (events.js:210:5)
    at e.exports.M (C:\Program Files\Anchor Wallet\resources\app.asar\webpack:\app\main.prod.js:213964:13)
    at e.exports.emit (events.js:210:5)
    at e.exports.controlMessage (C:\Program Files\Anchor Wallet\resources\app.asar\webpack:\app\main.prod.js:212311:12)
    at e.exports.getData (C:\Program Files\Anchor Wallet\resources\app.asar\webpack:\app\main.prod.js:212184:42)
    at e.exports.startLoop (C:\Program Files\Anchor Wallet\resources\app.asar\webpack:\app\main.prod.js:211987:22)
    at e.exports._write (C:\Program Files\Anchor Wallet\resources\app.asar\webpack:\app\main.prod.js:211923:10)
    at doWrite (_stream_writable.js:431:12)

[OK]
```

Version 1.2.6

**Comment by aaroncox** [comment] 2021-08-23 19:34
We have this error suppressed in 1.2.7 (which is out as a prerelease), but have heard reports that the failure to reconnect with that service is now just failing silently instead of reconnecting. I'm going to close this one as a duplicate of #1139 - feel free to join in the conversation there 👍

**Closed by aaroncox** 2021-08-23 19:34 UTC
