### ISSUE TITLE
site will not allow me to add my wax account

### ISSUE THREAD

**Issue by Knightsword27** [greymass/anchor#1238] opened 2022-02-20 16:23 UTC
I have no key, no number band I know nothing about ledger support, I am not a web genius I just want to wax account to Anchor so I can access Farmers World. There is no place to put my wax address. what am I doing wrong

**Comment by aaroncox** [comment] 2022-03-28 18:45
Apologies we missed this. Closing this out since it's not a bug report and more support related. If you're still having issues, please reach out to support@greymass.com.

**Closed by aaroncox** 2022-03-28 18:45 UTC
