### ISSUE TITLE
ERRORE ANCHOR WALLET

### ISSUE THREAD

**Issue by maghez** [greymass/anchor#1041] opened 2021-02-22 10:11 UTC
Hello, yesterday I tried to use my Anchor for Governance voting. I got this error ERROR: {“actor”. “Accountname”, “permission”. ". Password"}.
So I tried to do other operations, but it doesn't let me do anything, it always gives me an error of type. If I go to Airgrabs → WIZZ → claim, it gives me Airgrab error: Encoding error at root: Invalid type jsobj, no encoding methods implemented ().
I can't even send EOS to another wallet.
I also tried to connect to the wallet via eos authority, but when it connects to the anchor app it gives me a blocking error
Do you have any idea how this can be solved? Anchor is latest version.
Thank you
Maghez

**Comment by aaroncox** [comment] 2021-02-22 21:18
Saw you posted on the forums, we'll continue the discussion there and close this out.

**Closed by aaroncox** 2021-02-22 21:18 UTC

**Comment by guittarzzan** [comment] 2021-04-04 17:00
Did you ever find a solution to this?  I'm getting the same error trying to unstake or xfer eos in anchor wallet.
thanks

**Comment by aaroncox** [comment] 2021-04-04 18:25
The discussion was continued here if you wanted to follow along:

https://eoscommunity.org/t/errore-anchor-wallet/431

The problem is that the account isn't setup properly, and should be removed and re-added using the "Import Private Key" method.
