### ISSUE TITLE
Not able to import account with private key

### ISSUE THREAD

**Issue by nvzvhenry** [greymass/anchor#1219] opened 2021-11-26 02:34 UTC
Error: Invalid public key string
    at Function.from (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:210719)
    at file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:2217506
    at Array.forEach (<anonymous>)
    at c.value (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:2217450)
    at Wa (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3926265)
    at _a (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3926060)
    at Su (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3961674)
    at bc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3953115)
    at yc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3953040)
    at uc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3950070)

**Comment by aaroncox** [comment] 2021-11-26 03:23
Is this using the "Import via Private Key" option? 

If so, does the private key start with the number `5` or does it start with the letters `PVT`?

**Comment by aaroncox** [comment] 2021-11-26 03:28
Also - which version is this happening on?

**Comment by KleinSamuel** [comment] 2021-12-03 12:20
I encounter the same error each time I try to import a second account by private key.
When starting anchor, the process of importing an existing account by private key works fine. 
But when I try to add another, the above mentioned error occurs. 
Anchor needs to be restarted in order for this error to disappear, a simple "View > Reload (CTRL + R)" does not fix this error.

The version I am using is `linux-anchor-wallet-1.3.2-amd64.deb`

Steps to reproduce:
1) Create an account for the WAX testnet: https://waxsweden.org/create-testnet-account/
2) Start Anchor and add the WAX testnet blockchain
3) Choose "Manage Wallet" > "Import Account(s)" > "Import an existing Account" > "Import Private Key"
4) Add the private key for the in step 1) created account with active permission -> works as intended
5) Create an account for the WAX testnet: https://waxsweden.org/create-testnet-account/
6) Start Anchor and add the WAX testnet blockchain
7) Choose "Manage Wallet" > "Import Account(s)" > "Import an existing Account" > "Import Private Key"
8) Add the private key for the in step 5) created account with active permission -> the above mentioned error occurs

**Comment by iNF3RNO92** [comment] 2021-12-11 04:50
Just replicated on v1.3.2 - windows 11
Key started with PVT

Error: Invalid public key string
    at Function.from (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:210719)
    at file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:2217506
    at Array.forEach (<anonymous>)
    at c.value (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:2217450)
    at Wa (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3926265)
    at _a (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3926060)
    at Su (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3961674)
    at bc (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3953115)
    at yc (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3953040)
    at uc (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3950070)

**Comment by DLCManager** [comment] 2021-12-28 08:41
The same error. Windows 10 with latest updates, Anchor 1.3.2. Error gets if want to import more than 1 account (Import Private Key).

![error_anchor](https://user-images.githubusercontent.com/72817541/147546660-596dddbf-996b-4bc8-874e-4d4599b073aa.png)

**Comment by aaroncox** [comment] 2021-12-29 03:18
Thanks for the detailed report @iNF3RNO92.

We have been tied up on some other projects these past few weeks, but will start investigating and trying to reproduce this sometime early in the new year. Apologies for the delay!

**Comment by aaroncox** [comment] 2022-04-06 22:10
I believe Anchor 1.3.3 resolves this issue - closing this out but feel free to reopen if this is still happening.

**Closed by aaroncox** 2022-04-06 22:10 UTC
