### ISSUE TITLE
Manage wallets -> Import Accounts -> Import an existing account  -> Import an existing Private Key

### ISSUE THREAD

**Issue by songproducer** [greymass/anchor#1252] opened 2022-03-28 09:35 UTC
Error: Invalid public key string
    at Function.from (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:210719)
    at file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:2217506
    at Array.forEach (<anonymous>)
    at c.value (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:2217450)
    at Wa (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3926265)
    at _a (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3926060)
    at Su (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3961674)
    at bc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3953115)
    at yc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3953040)
    at uc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3950070)

**Comment by aaroncox** [comment] 2022-03-28 18:41
Duplicate of #1244 - which will be fixed in version 1.3.3 👍

**Closed by aaroncox** 2022-03-28 18:41 UTC
