### ISSUE TITLE
Failed to unlock new wallet|Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by sss-CRS-sss** [greymass/anchor#1043] opened 2021-02-24 11:22 UTC
1) Run anchor 1.1.12(also 1.1.8).
2) Go to Tools -> Reset Application -> OK
3) Setup wallet - > enter any password, for example 123
4) Go to Tools -> tool menu v1 -> Wallet Tools -> Permission
5) Click Unlock wallet - > enter 123 and... nothing. In dev log error not found file:
![1error_anchor](https://user-images.githubusercontent.com/38219101/108993160-01240880-76bc-11eb-93d2-439eb7a785e6.jpg)

Also:
step in 1-3 again
4) Select EOS blockchain
5) Go to Tools -> tool menu v1 -> Wallet Tools -> Delegation
6) get error in dev log:
![2error_anchor](https://user-images.githubusercontent.com/38219101/108993386-53652980-76bc-11eb-896a-68796eb537b0.jpg)
7) enter password 123 and get error Failed to unlock wallet

**Comment by aaroncox** [comment] 2021-02-24 18:35
Based on the first screenshot, it looks like the API node is unset for some reason. 

Go into "Manage Blockchains" from the dropdown in the upper left, and click the gear next to the network you want to edit. In the API node field, enter a valid API node URL and save it, then click the blockchain to select it again.

You can use our node, the URL is `https://eos.greymass.com`.

![apinode](https://user-images.githubusercontent.com/677686/109048496-222d2f00-76a5-11eb-9c4a-73c981b64099.gif)

**Comment by aaroncox** [comment] 2021-02-24 18:36
We'll also do some investigation as to why this value could possible be null.

**Comment by aaroncox** [comment] 2021-04-05 23:18
So the issue here is that you shouldn't be able to access the permissions section until you actually setup an account. Took me a while but after following these exact instructions I reproduced and realized this was the situation. There will be a fix for this in 1.2.1.

**Closed** 2021-04-07 21:28 UTC
