### ISSUE TITLE
Bug in backup recovery process

### ISSUE THREAD

**Issue by RalfWeinand** [greymass/anchor#1269] opened 2022-04-16 02:25 UTC
### Description

There is something broken with the backup/restore mechanism in Anchor. I did perform a backup from Anchor Wallet 1.2.9 on Linux (Ubuntu 20.04). When I try to import it on my new Macbook Pro (M1) v12.3.1 it just keeps spinning and never completes.

If I kill it after a few minutes of spinning and try and re-open there's nothing imported.

So not sure if it's an incompatibility issue between the two different versions 1.2.9 versus 1.3.4 or between Linux and Mac version, or possibly because I had some custom blockchains defined in the version on Linux that it doesn't have after a fresh install of Anchor on my Mac (or a combination of those).

### Platform

Desktop (MacOS)

### Steps To Reproduce

1. Create wallet on Linux Ubuntu Anchor. Import several keys, including for some custom networks.
2. Backup wallet to JSON file
3. Copy JSON backup to Macbook
4. Try to initialise fresh install of Anchor 1.3.4 from the JSON backup file

### Contact Details

ralf.weinand@gmail.com

**Comment by RalfWeinand** [comment] 2022-04-20 22:29
This is what that looks like. 

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/1137211/164335226-a6f56f3f-6a09-4cbe-b8d3-27d4d4cc2a8d.png">

**Comment by aaroncox** [comment] 2022-04-21 01:39
Perfect, thank you. 

It looks like the error is being caused by an undefined API node in the backup. I'll see if we can wrap some checks around that and get it fixed in the next release!

**Comment by RalfWeinand** [comment] 2022-04-21 02:33
Thanks Arron, yes - I remember I was testing a few different APIs at some point as I was getting a weird error. Probably best if the backup import can fall back to a default API if it times out. Send me a ping when you want me to retest this bug in the next minor release.

**Closed** 2022-07-28 18:09 UTC
Labels: bug, anchor
