### ISSUE TITLE
error after loading proton wallet key PVT_K1_

### ISSUE THREAD

**Issue by marcinch18** [greymass/anchor#1231] opened 2022-01-07 12:18 UTC
Error: Invalid public key string
    at Function.from (file:///E:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:210719)
    at file:///E:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:2217506
    at Array.forEach (<anonymous>)
    at c.value (file:///E:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:2217450)
    at Wa (file:///E:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3926265)
    at _a (file:///E:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3926060)
    at Su (file:///E:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3961674)
    at bc (file:///E:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3953115)
    at yc (file:///E:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3953040)
    at uc (file:///E:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3950070)

**Comment by aaroncox** [comment] 2022-01-30 17:26
Duplicate of #1232 - closing this one out.

**Closed by aaroncox** 2022-01-30 17:26 UTC
