### ISSUE TITLE
Update version cannot import account

### ISSUE THREAD

**Issue by taddrous** [greymass/anchor#1239] opened 2022-02-22 01:00 UTC
Dear Sir,
I have a serious problem about import account. I was installed anchor app version 1.3.2 Then I created new wallet and imported to the app then I made the transections as normal after finished I want to add my another wallet to the app but the version can not import the second one. Then I download version 1.3.1 to install with out back up private key of the first one because I assume its will be automatic to sync to the new version I did attended to write down the key by manual after finish all process . After install I can not import my first one to the wallet because it asked for private key. How can I do to recover my wallet? I use the same computer. Please advice me I really need your help.

**Comment by aaroncox** [comment] 2022-03-28 18:44
Apologies we missed this. Closing this out since it's not a bug report and more support related. If you're still having issues, please reach out to support@greymass.com.

**Closed by aaroncox** 2022-03-28 18:44 UTC
